.PHONY: clean All

All:
	@echo "----------Building project:[ 121 - Debug ]----------"
	@"$(MAKE)" -f  "121.mk"
clean:
	@echo "----------Cleaning project:[ 121 - Debug ]----------"
	@"$(MAKE)" -f  "121.mk" clean
